### ISSUE TITLE
Latest Version and Android X support

### ISSUE THREAD

**Issue by hackdonn** [robbyrahmana/todoApp#8]
Hey can you please update this project to new version of flutter and remove the depreciated things! 
And also make it androidX supportable so that I can be used for publication!

Thanks in advance!

Waiting for positive response from you!
keep up the good work!

**Comment by robbyrahmana** [comment]
All version updated, please refer to this link

https://github.com/robbyrahmana/todoApp/commit/373a97709fe703af308ddfd750826e1db2e1dcdb
